[2024-02-24T07:43:32.416+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chinook_to_google_sheet.execute_sql_task manual__2024-02-24T07:43:29+00:00 [queued]>
[2024-02-24T07:43:32.421+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chinook_to_google_sheet.execute_sql_task manual__2024-02-24T07:43:29+00:00 [queued]>
[2024-02-24T07:43:32.423+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-24T07:43:32.430+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): execute_sql_task> on 2024-02-24 07:43:29+00:00
[2024-02-24T07:43:32.436+0000] {standard_task_runner.py:60} INFO - Started process 2755 to run task
[2024-02-24T07:43:32.440+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'chinook_to_google_sheet', 'execute_sql_task', 'manual__2024-02-24T07:43:29+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/chinook_to_google_sheet.py', '--cfg-path', '/tmp/tmp76_nuq20']
[2024-02-24T07:43:32.442+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask execute_sql_task
[2024-02-24T07:43:32.474+0000] {task_command.py:423} INFO - Running <TaskInstance: chinook_to_google_sheet.execute_sql_task manual__2024-02-24T07:43:29+00:00 [running]> on host 442819554f8d
[2024-02-24T07:43:32.502+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'execute_sql_task', field 'sql'. Template: '../db/chinook.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 194, in get_source
    pieces = split_template_path(template)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 35, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../db/chinook.sql
[2024-02-24T07:43:32.505+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 194, in get_source
    pieces = split_template_path(template)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 35, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../db/chinook.sql
[2024-02-24T07:43:32.513+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=chinook_to_google_sheet, task_id=execute_sql_task, execution_date=20240224T074329, start_date=20240224T074332, end_date=20240224T074332
[2024-02-24T07:43:32.520+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 37 for task execute_sql_task (../db/chinook.sql; 2755)
[2024-02-24T07:43:32.541+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-24T07:43:32.556+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
