[2024-02-24T00:37:43.383+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dibimbing_example_17.task1 scheduled__2024-02-23T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
